export function getFlagForCategory(name: string): string {
  const lower = name.toLowerCase();
  if (lower.match(/\b(us|usa|united states)\b/)) return '🇺🇸';
  if (lower.match(/\b(uk|en|english|united kingdom)\b/)) return '🇬🇧';
  if (lower.match(/\b(fr|france|french)\b/)) return '🇫🇷';
  if (lower.match(/\b(de|germany|german)\b/)) return '🇩🇪';
  if (lower.match(/\b(it|italy|italian)\b/)) return '🇮🇹';
  if (lower.match(/\b(es|spain|spanish)\b/)) return '🇪🇸';
  if (lower.match(/\b(ar|arabic|arab)\b/)) return '🇸🇦';
  if (lower.match(/\b(tr|turkey|turkish)\b/)) return '🇹🇷';
  if (lower.match(/\b(pt|portugal|portuguese)\b/)) return '🇵🇹';
  if (lower.match(/\b(nl|netherlands|dutch)\b/)) return '🇳🇱';
  if (lower.match(/\b(ru|russia|russian)\b/)) return '🇷🇺';
  if (lower.match(/\b(in|india|indian)\b/)) return '🇮🇳';
  if (lower.match(/\b(br|brazil|brazilian)\b/)) return '🇧🇷';
  if (lower.match(/\b(mx|mexico|mexican)\b/)) return '🇲🇽';
  if (lower.match(/\b(ca|canada|canadian)\b/)) return '🇨🇦';
  if (lower.match(/\b(au|australia|australian)\b/)) return '🇦🇺';
  if (lower.match(/\b(pl|poland|polish)\b/)) return '🇵🇱';
  if (lower.match(/\b(ro|romania|romanian)\b/)) return '🇷🇴';
  if (lower.match(/\b(gr|greece|greek)\b/)) return '🇬🇷';
  if (lower.match(/\b(se|sweden|swedish)\b/)) return '🇸🇪';
  if (lower.match(/\b(no|norway|norwegian)\b/)) return '🇳🇴';
  if (lower.match(/\b(dk|denmark|danish)\b/)) return '🇩🇰';
  if (lower.match(/\b(fi|finland|finnish)\b/)) return '🇫🇮';
  if (lower.match(/\b(ch|switzerland|swiss)\b/)) return '🇨🇭';
  if (lower.match(/\b(at|austria|austrian)\b/)) return '🇦🇹';
  if (lower.match(/\b(be|belgium|belgian)\b/)) return '🇧🇪';
  if (lower.match(/\b(za|south africa)\b/)) return '🇿🇦';
  if (lower.match(/\b(kr|korea|korean)\b/)) return '🇰🇷';
  if (lower.match(/\b(jp|japan|japanese)\b/)) return '🇯🇵';
  if (lower.match(/\b(cn|china|chinese|zh)\b/)) return '🇨🇳';
  if (lower.match(/\b(pk|pakistan|pakistani)\b/)) return '🇵🇰';
  if (lower.match(/\b(bd|bangladesh|bengali)\b/)) return '🇧🇩';
  if (lower.match(/\b(ma|morocco|moroccan)\b/)) return '🇲🇦';
  if (lower.match(/\b(dz|algeria|algerian)\b/)) return '🇩🇿';
  if (lower.match(/\b(tn|tunisia|tunisian)\b/)) return '🇹🇳';
  if (lower.match(/\b(eg|egypt|egyptian)\b/)) return '🇪🇬';
  if (lower.match(/\b(ae|uae|emirates)\b/)) return '🇦🇪';
  if (lower.match(/\b(sa|saudi)\b/)) return '🇸🇦';
  if (lower.match(/\b(qa|qatar)\b/)) return '🇶🇦';
  if (lower.match(/\b(kw|kuwait)\b/)) return '🇰🇼';
  if (lower.match(/\b(bh|bahrain)\b/)) return '🇧🇭';
  if (lower.match(/\b(om|oman)\b/)) return '🇴🇲';
  if (lower.match(/\b(iq|iraq|iraqi)\b/)) return '🇮🇶';
  if (lower.match(/\b(sy|syria|syrian)\b/)) return '🇸🇾';
  if (lower.match(/\b(lb|lebanon|lebanese)\b/)) return '🇱🇧';
  if (lower.match(/\b(jo|jordan|jordanian)\b/)) return '🇯🇴';
  if (lower.match(/\b(ps|palestine|palestinian)\b/)) return '🇵🇸';
  if (lower.match(/\b(ye|yemen|yemeni)\b/)) return '🇾🇪';
  if (lower.match(/\b(sd|sudan|sudanese)\b/)) return '🇸🇩';
  if (lower.match(/\b(ly|libya|libyan)\b/)) return '🇱🇾';
  if (lower.match(/\b(africa|african)\b/)) return '🌍';
  if (lower.match(/\b(asia|asian)\b/)) return '🌏';
  if (lower.match(/\b(europe|european)\b/)) return '🇪🇺';
  if (lower.match(/\b(latino|latin)\b/)) return '🌎';
  if (lower.match(/\b(vip|premium|4k|fhd|hd|sd)\b/)) return '⭐';
  if (lower.match(/\b(kids|children)\b/)) return '👶';
  if (lower.match(/\b(news)\b/)) return '📰';
  if (lower.match(/\b(music)\b/)) return '🎵';
  if (lower.match(/\b(sports|sport)\b/)) return '⚽';
  if (lower.match(/\b(movies|movie|cinema)\b/)) return '🎬';
  if (lower.match(/\b(series|tv shows)\b/)) return '📺';
  if (lower.match(/\b(documentary|documentaries)\b/)) return '🦁';
  if (lower.match(/\b(xxx|adult)\b/)) return '🔞';
  return '📺'; // Default fallback
}
